default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_development
  username: rails_dev
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: bookstore_test
  host: localhost
  port: 5432
  username: rails_dev
  password: postgres

production:
  <<: *default
  adapter: postgresql
  database: bookstore_production
  username: bookstore
  password: <%= ENV['BOOKSTORE_DATABASE_PASSWORD'] %>
